language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - DJANGO_PACKAGE="Django>=1.8,<1.9"
    - DJANGO_PACKAGE="Django>=1.9,<1.10"
    - DJANGO_PACKAGE="Django==1.11b1"
install: pip install $DJANGO_PACKAGE
script: PYTHONPATH=. DJANGO_SETTINGS_MODULE=tests.test_settings django-admin test
notifications:
    email:
        - james.p.turk@gmail.com
